themed_fast_404.settings:
  type: config_object
  mapping:
    base_url:
      type: string
      label: 'Base URL'
      translatable: true
    404_body:
      type: string
      label: '404 Page body'
      translatable: true
